### ISSUE TITLE
Mod now required on client-side

### ISSUE THREAD

**Issue by qixils** [OnyxStudios/Cardinal-Components-API#174]
I'm running a server with just [my mod](https://github.com/qixils/minecraft-crowdcontrol/tree/master/fabric) which bundles `cardinal-components-entity` and am unable to join unless I also install the mod in the client due to error `Client disconnected with reason: This server requires Cardinal Components API (unhandled packet: cardinal-components:entity_sync)`. This is a new regression introduced in 1.20.5+ / v6.

![image](https://github.com/Ladysnake/Cardinal-Components-API/assets/13265322/221f0705-99bc-43ff-9d53-8f29d0f31537)

https://github.com/Ladysnake/Cardinal-Components-API/assets/13265322/7824442b-f424-41e0-b6d3-c76d91ad0f0b

**Comment by qixils** [comment]
Might be related to / duplicate of #173? Sounds similar but I'm not using scoreboards just entities

**Comment by Pyrofab** [comment]
Hello, this is addressed in the migration guide : https://ladysnake.org/wiki/cardinal-components-api/upgrade-instructions/CCA-6-changes#client-optional-components

Could you try again with the relevant override on your component ? (Assuming your mod does use `AutoSyncedComponent` somewhere)

**Comment by qixils** [comment]
Apologies, works now.
