### ISSUE TITLE
My Minecraft Crashes Upon Opening a World

### ISSUE THREAD

**Issue by CaptianPython12** [OnyxStudios/Cardinal-Components-API#180]
https://pastebin.com/YkbM15eb
im in version 1.20.1 of minecraft and fabric loader 0.15.11
from what i understand its something to do with the entitys but idk how to fix it

**Comment by CaptianPython12** [comment]
help pls

**Comment by Pyrofab** [comment]
Your version of dyed item frames is bundling Cardinal Components API for 1.20.3, not for 1.20.1. You can try installing the right version directly from here : https://modrinth.com/mod/cardinal-components-api/version/5.2.2
