### ISSUE TITLE
Update to 1.21.2/3

### ISSUE THREAD

**Issue by Patbox** [OnyxStudios/Cardinal-Components-API#185]
Current latest version isn't compatible with 1.21.2 changes, requiring an update.

**Comment by Pyrofab** [comment]
True. Do you have a PR ready ? Otherwise I can do it a bit later today

**Comment by Patbox** [comment]
Nope, took a quick look and made a really dirty patch for my mod (since I only used base and world). But test mods and chunk one require most changes from quick look

**Comment by Pyrofab** [comment]
Done, apologies for the delay - was a fairly busy week for me.
