### ISSUE TITLE
maven does not contain current releases

### ISSUE THREAD

**Issue by Linguardium** [OnyxStudios/Cardinal-Components-API#19]
while this error makes sense due to the breakouts happening after version 1.2.1, the main readme shows that including the base API jar should work via buildscript.
additionally, the item component is only at version 2.3.0 and does not contain some critical fixes between 2.3.0 and 2.3.4

Adding the repository and dependency clauses to the build script using the current version (2.3.4) in releases gives the error:

`A problem occurred configuring root project 'LivingItems'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find com.github.NerdHubMC:Cardinal-Components-API:2.3.4.
     Searched in the following locations:
       - https://libraries.minecraft.net/com/github/NerdHubMC/Cardinal-Components-API/2.3.4/Cardinal-Components-API-2.3.4.pom
       - https://libraries.minecraft.net/com/github/NerdHubMC/Cardinal-Components-API/2.3.4/Cardinal-Components-API-2.3.4.jar
       - https://maven.onyxstudios.dev/com/github/NerdHubMC/Cardinal-Components-API/2.3.4/Cardinal-Components-API-2.3.4.pom
       - https://maven.onyxstudios.dev/com/github/NerdHubMC/Cardinal-Components-API/2.3.4/Cardinal-Components-API-2.3.4.jar
       - file:/C:/Users/User/.gradle/caches/fabric-loom/Cardinal-Components-API-2.3.4.jar
       - file:/C:/Users/User/.gradle/caches/fabric-loom/Cardinal-Components-API.jar
       - file:/C:/Users/User/source/fabric_minecraft/LivingItems/build/loom-cache/Cardinal-Components-API-2.3.4.jar
       - file:/C:/Users/User/source/fabric_minecraft/LivingItems/build/loom-cache/Cardinal-Components-API.jar
       - file:/C:/Users/User/source/fabric_minecraft/LivingItems/.gradle/loom-cache/remapped_mods/Cardinal-Components-API-2.3.4.jar
       - file:/C:/Users/User/source/fabric_minecraft/LivingItems/.gradle/loom-cache/remapped_mods/Cardinal-Components-API.jar
       - https://maven.fabricmc.net/com/github/NerdHubMC/Cardinal-Components-API/2.3.4/Cardinal-Components-API-2.3.4.pom
       - https://maven.fabricmc.net/com/github/NerdHubMC/Cardinal-Components-API/2.3.4/Cardinal-Components-API-2.3.4.jar
       - https://repo.maven.apache.org/maven2/com/github/NerdHubMC/Cardinal-Components-API/2.3.4/Cardinal-Components-API-2.3.4.pom
       - https://repo.maven.apache.org/maven2/com/github/NerdHubMC/Cardinal-Components-API/2.3.4/Cardinal-Components-API-2.3.4.jar
       - https://jcenter.bintray.com/com/github/NerdHubMC/Cardinal-Components-API/2.3.4/Cardinal-Components-API-2.3.4.pom
       - https://jcenter.bintray.com/com/github/NerdHubMC/Cardinal-Components-API/2.3.4/Cardinal-Components-API-2.3.4.jar
     Required by:
         project :
   > Could not find com.github.NerdHubMC.Cardinal-Components-API:cardinal-components-item:2.3.4.
     Searched in the following locations:
       - https://libraries.minecraft.net/com/github/NerdHubMC/Cardinal-Components-API/cardinal-components-item/2.3.4/cardinal-components-item-2.3.4.pom
       - https://libraries.minecraft.net/com/github/NerdHubMC/Cardinal-Components-API/cardinal-components-item/2.3.4/cardinal-components-item-2.3.4.jar
       - https://maven.onyxstudios.dev/com/github/NerdHubMC/Cardinal-Components-API/cardinal-components-item/2.3.4/cardinal-components-item-2.3.4.pom
       - https://maven.onyxstudios.dev/com/github/NerdHubMC/Cardinal-Components-API/cardinal-components-item/2.3.4/cardinal-components-item-2.3.4.jar
       - file:/C:/Users/User/.gradle/caches/fabric-loom/cardinal-components-item-2.3.4.jar
       - file:/C:/Users/User/.gradle/caches/fabric-loom/cardinal-components-item.jar
       - file:/C:/Users/User/source/fabric_minecraft/LivingItems/build/loom-cache/cardinal-components-item-2.3.4.jar
       - file:/C:/Users/User/source/fabric_minecraft/LivingItems/build/loom-cache/cardinal-components-item.jar
       - file:/C:/Users/User/source/fabric_minecraft/LivingItems/.gradle/loom-cache/remapped_mods/cardinal-components-item-2.3.4.jar
       - file:/C:/Users/User/source/fabric_minecraft/LivingItems/.gradle/loom-cache/remapped_mods/cardinal-components-item.jar
       - https://maven.fabricmc.net/com/github/NerdHubMC/Cardinal-Components-API/cardinal-components-item/2.3.4/cardinal-components-item-2.3.4.pom
       - https://maven.fabricmc.net/com/github/NerdHubMC/Cardinal-Components-API/cardinal-components-item/2.3.4/cardinal-components-item-2.3.4.jar
       - https://repo.maven.apache.org/maven2/com/github/NerdHubMC/Cardinal-Components-API/cardinal-components-item/2.3.4/cardinal-components-item-2.3.4.pom
       - https://repo.maven.apache.org/maven2/com/github/NerdHubMC/Cardinal-Components-API/cardinal-components-item/2.3.4/cardinal-components-item-2.3.4.jar
       - https://jcenter.bintray.com/com/github/NerdHubMC/Cardinal-Components-API/cardinal-components-item/2.3.4/cardinal-components-item-2.3.4.pom
       - https://jcenter.bintray.com/com/github/NerdHubMC/Cardinal-Components-API/cardinal-components-item/2.3.4/cardinal-components-item-2.3.4.jar
     Required by:
         project :
`
` Possible solution:
` - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by UpcraftLP** [comment]
yes, the current build scripts are broken, I haven't had time to fix that.

use [JitPack](https://jitpack.io/#OnyxStudios/Cardinal-Components-API/ "Cardinal Components on JitPack") for now

**Comment by Linguardium** [comment]
yep, thats what i ended up doing, but i figured i would open an issue since people are directed to do it the other way

**Comment by Geometrically** [comment]
Fixed in https://github.com/OnyxStudios/Cardinal-Components-API/pull/21

**Comment by Linguardium** [comment]
not fixed in #21

**Comment by UpcraftLP** [comment]
#22 updated the readme to use jitpack instead of the maven, tho that is only a temporary solution.

**Comment by UpcraftLP** [comment]
Update: The maven does now contain current releases, however the main module's POM file does not export dependencies on the sub-modules.
