### ISSUE TITLE
Static Components Feedback

### ISSUE THREAD

**Issue by Pyrofab** [OnyxStudios/Cardinal-Components-API#25]
#23 added statically declared components as an experimental feature. This issue is for sharing observations and thoughts about that new system.

## Annotations
**Update: annotations are no more**

What is your stance on magical annotations to declare component factories ? Would you rather declare them entirely in `fabric.mod.json` ?

For example, replacing
```json
{
    "custom": {
        "cardinal-components-api:component-factories": [
            "io.github.mymod.MyComponents"
        ]
    }
}
```
```java
    @EntityComponentFactory(value = "mymod:mycomponent", target = LivingEntity.class)
    public static MyComponent create(LivingEntity e /* optional arg */) {
        return new MyEntityComponent(e);
    }
```
with
```json
{
    "custom": {
        "cardinal-components-api:component-factories": [
            {
                "type": "entity",
                "target": "net.minecraft.class_1309",
                "factory": "io.github.mymod.MyComponents::create"
             }
        ]
    }
}
```
```java
    public static MyComponent create(LivingEntity e /* optional arg */) {
        return new MyEntityComponent(e);
    }
```

**Comment by enderger** [comment]
Problems may arise when working with non-Java projects (Kotlin, Scala, etc.)

**Comment by Pyrofab** [comment]
The 3.0 API having entered its stable stage, I believe this is a good time to close this issue. Thanks for the bit of feedback.
